services:
  traefik:
    image: traefik:v3.6
    container_name: traefik-app
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
      - "--entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=shepreneurinfo@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`localhost`)
      - traefik.http.routers.app.entrypoints=web,websecure
      - traefik.http.routers.app.tls.certresolver=myresolver
      - traefik.http.routers.app.tls=false
      - traefik.http.services.app.loadbalancer.server.port=8080
    # env_file:
    #   - .env
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    depends_on:
      - server
    networks:
      - proxy

  server:
    image: imshibaji/jobs-api-server:latest
    container_name: server_app
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`api.localhost`)
      - traefik.http.routers.server.entrypoints=web,websecure
      - traefik.http.routers.server.tls.certresolver=myresolver
      - traefik.http.routers.server.tls=false
      - traefik.http.services.server.loadbalancer.server.port=3300

    environment:
      NODE_ENV: production
      APP_NAME: "Jobs API Server"
      APP_VERSION: 1.0.5
      APP_ENV: production
      APP_HOST: 0.0.0.0
      APP_PORT: 3300
      APP_SECRET_KEY: asdrweweddsaxadasfsdfdsfgdffcr4fsw3232edwssdzcsdsdf
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: jobs_for_woman
      DB_USER: postgres
      DB_PASS: Spaceranger@123
      DB_SYNC: true
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: Spaceranger@123
    ports:
      - 3300:3300
    # expose:
    #   - 3300
    volumes:
      - ./uploads:/app/uploads:rw
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: db_app
    restart: always
    user: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jobs_for_woman
      - POSTGRES_PASSWORD=Spaceranger@123
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis_app
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_PASSWORD=Spaceranger@123

volumes:
  server_app:
    driver: local
  db_data:
  redis_data:

networks:
  proxy: